"""initial schema

Revision ID: 8feb10d94e59
Revises: 
Create Date: 2026-09-28 21:37:46.581561

"""
from alembic import op
import sqlalchemy as sa


revision = '8feb10d94e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Requerido para las restricciones EXCLUDE con daterange más abajo.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callgrid_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callgrid_sub_id', sa.Integer(), nullable=False),
    sa.Column('callgrid_source_raw_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callgrid_sub_id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('callgrid_vendor_sub_id', sa.Integer(), nullable=False),
    sa.Column('callgrid_vendor_raw_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callgrid_vendor_sub_id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='sync_status'), nullable=False),
    sa.Column('pivot_used', sa.Text(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('sources_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_payout_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callgrid_source_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('ended_count', sa.Integer(), nullable=False),
    sa.Column('connected_count', sa.Integer(), nullable=False),
    sa.Column('billable_count', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['callgrid_source_id'], ['callgrid_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_payout_history_callgrid_source_id'), 'call_payout_history', ['callgrid_source_id'], unique=False)
    op.create_index(op.f('ix_call_payout_history_metric_date'), 'call_payout_history', ['metric_date'], unique=False)
    op.create_table('daily_callgrid_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callgrid_source_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('ended_count', sa.Integer(), nullable=False),
    sa.Column('connected_count', sa.Integer(), nullable=False),
    sa.Column('billable_count', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['callgrid_source_id'], ['callgrid_sources.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callgrid_source_id', 'metric_date')
    )
    op.create_index(op.f('ix_daily_callgrid_metrics_callgrid_source_id'), 'daily_callgrid_metrics', ['callgrid_source_id'], unique=False)
    op.create_index(op.f('ix_daily_callgrid_metrics_metric_date'), 'daily_callgrid_metrics', ['metric_date'], unique=False)
    op.create_table('media_buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_buyers_partner_id'), 'media_buyers', ['partner_id'], unique=False)
    op.create_table('media_buyer_source_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_buyer_id', sa.Integer(), nullable=False),
    sa.Column('callgrid_source_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['callgrid_source_id'], ['callgrid_sources.id'], ),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_buyer_source_mappings_callgrid_source_id'), 'media_buyer_source_mappings', ['callgrid_source_id'], unique=False)
    op.create_index(op.f('ix_media_buyer_source_mappings_media_buyer_id'), 'media_buyer_source_mappings', ['media_buyer_id'], unique=False)
    # Invariante: una CallgridSource nunca mapea a dos media buyers el mismo día.
    op.execute("""
        ALTER TABLE media_buyer_source_mappings
        ADD CONSTRAINT excl_source_mapping_no_overlap
        EXCLUDE USING gist (
            callgrid_source_id WITH =,
            daterange(effective_from, effective_to, '[)') WITH &&
        )
    """)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ROYALSPACE_ADMIN', 'DIXON_MANAGER', 'MEDIA_BUYER', name='user_role'), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('media_buyer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ad_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_buyer_id', sa.Integer(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['ad_spend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_spend_media_buyer_id'), 'ad_spend', ['media_buyer_id'], unique=False)
    op.create_index(op.f('ix_ad_spend_spend_date'), 'ad_spend', ['spend_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('compensation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_buyer_id', sa.Integer(), nullable=False),
    sa.Column('mb_percentage_bps', sa.SmallInteger(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mb_percentage_bps BETWEEN 0 AND 10000', name='ck_comp_rule_bps_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_rules_media_buyer_id'), 'compensation_rules', ['media_buyer_id'], unique=False)
    # effective_from siempre debe ser lunes — así una sola liquidación semanal
    # (Mon-Sun) nunca cruza dos tasas de compensación distintas.
    op.execute("""
        ALTER TABLE compensation_rules
        ADD CONSTRAINT ck_comp_rule_effective_from_monday
        CHECK (EXTRACT(ISODOW FROM effective_from) = 1)
    """)
    # Invariante: un media buyer nunca tiene dos tasas vigentes al mismo tiempo.
    op.execute("""
        ALTER TABLE compensation_rules
        ADD CONSTRAINT excl_comp_rule_no_overlap
        EXCLUDE USING gist (
            media_buyer_id WITH =,
            daterange(effective_from, effective_to, '[)') WITH &&
        )
    """)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_buyer_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reporting_timezone', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING_RECONCILIATION', 'READY', 'APPROVED', 'PAID', 'LOCKED', name='settlement_status'), nullable=False),
    sa.Column('compensation_rule_id', sa.Integer(), nullable=True),
    sa.Column('mb_percentage_bps_snapshot', sa.SmallInteger(), nullable=False),
    sa.Column('gross_payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('ad_spend_cents', sa.BigInteger(), nullable=False),
    sa.Column('incoming_deficit_cents', sa.BigInteger(), nullable=False),
    sa.Column('post_settlement_adjustment_cents', sa.BigInteger(), nullable=False),
    sa.Column('net_profit_cents', sa.BigInteger(), nullable=False),
    sa.Column('mb_earnings_cents', sa.BigInteger(), nullable=False),
    sa.Column('dixon_earnings_cents', sa.BigInteger(), nullable=False),
    sa.Column('outgoing_deficit_cents', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compensation_rule_id'], ['compensation_rules.id'], ),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_buyer_id', 'period_start', name='uq_settlement_mb_period')
    )
    op.create_index(op.f('ix_settlements_media_buyer_id'), 'settlements', ['media_buyer_id'], unique=False)
    op.create_table('financial_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_buyer_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('BONUS', 'CHARGEBACK', 'CORRECTION', 'POST_SETTLEMENT_CALLGRID_ADJUSTMENT', name='adjustment_type'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_settlement_id', sa.Integer(), nullable=True),
    sa.Column('applied_to_settlement_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'VOIDED', name='adjustment_status'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applied_to_settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_buyer_id'], ['media_buyers.id'], ),
    sa.ForeignKeyConstraint(['source_settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_adjustments_media_buyer_id'), 'financial_adjustments', ['media_buyer_id'], unique=False)
    op.create_table('settlement_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('callgrid_source_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('ended_count', sa.Integer(), nullable=False),
    sa.Column('connected_count', sa.Integer(), nullable=False),
    sa.Column('billable_count', sa.Integer(), nullable=False),
    sa.Column('ad_spend_cents', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['callgrid_source_id'], ['callgrid_sources.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_line_items_settlement_id'), 'settlement_line_items', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_line_items_settlement_id'), table_name='settlement_line_items')
    op.drop_table('settlement_line_items')
    op.drop_index(op.f('ix_financial_adjustments_media_buyer_id'), table_name='financial_adjustments')
    op.drop_table('financial_adjustments')
    op.drop_index(op.f('ix_settlements_media_buyer_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_compensation_rules_media_buyer_id'), table_name='compensation_rules')
    op.drop_table('compensation_rules')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ad_spend_spend_date'), table_name='ad_spend')
    op.drop_index(op.f('ix_ad_spend_media_buyer_id'), table_name='ad_spend')
    op.drop_table('ad_spend')
    op.drop_table('users')
    op.drop_index(op.f('ix_media_buyer_source_mappings_media_buyer_id'), table_name='media_buyer_source_mappings')
    op.drop_index(op.f('ix_media_buyer_source_mappings_callgrid_source_id'), table_name='media_buyer_source_mappings')
    op.drop_table('media_buyer_source_mappings')
    op.drop_index(op.f('ix_media_buyers_partner_id'), table_name='media_buyers')
    op.drop_table('media_buyers')
    op.drop_index(op.f('ix_daily_callgrid_metrics_metric_date'), table_name='daily_callgrid_metrics')
    op.drop_index(op.f('ix_daily_callgrid_metrics_callgrid_source_id'), table_name='daily_callgrid_metrics')
    op.drop_table('daily_callgrid_metrics')
    op.drop_index(op.f('ix_call_payout_history_metric_date'), table_name='call_payout_history')
    op.drop_index(op.f('ix_call_payout_history_callgrid_source_id'), table_name='call_payout_history')
    op.drop_table('call_payout_history')
    op.drop_table('sync_runs')
    op.drop_table('partners')
    op.drop_table('callgrid_sources')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
