"""add meta_ad_account_id to media_buyers

Revision ID: a988f6481b3a
Revises: 8feb10d94e59
Create Date: 2026-09-29 09:08:32.383467

"""
from alembic import op
import sqlalchemy as sa


revision = 'a988f6481b3a'
down_revision = '8feb10d94e59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_buyers', sa.Column('meta_ad_account_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_buyers', 'meta_ad_account_id')
    # ### end Alembic commands ###
